FROM golang:1.9 AS build

ENV VERSION latest
RUN go get -u github.com/golang/dep/cmd/dep
COPY . /go/src/github.com/container-bootcamp/einbuchen/
WORKDIR /go/src/github.com/container-bootcamp/einbuchen/
RUN dep ensure
RUN	GOARCH=amd64 CGO_ENABLED=0 go install \
    -installsuffix 'static' \
    -ldflags '-X $(PKG)/pkg/version.VERSION=$(VERSION)' \
    ./...

FROM scratch
WORKDIR /
COPY --from=build /go/bin/einbuchen /einbuchen
ADD resources/ /resources/
ENTRYPOINT ["/einbuchen"]
