[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/manucorporat/sse"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mongodb/mongo-tools"
  version = "2.7.8"

[[constraint]]
  branch = "master"
  name = "github.com/rwynn/gtm"
